locale: "en-US"
title: Portfolio - Kasper Birkelund # Title of your site
url: "http://kasper-birkelund.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Data Science portfolio - Kasper Birkelund

# Author details for the jekyll-seo-tag gem
author:
  name: Kasper Birkelund
  email: kasper.s.birkelund@gmail.com

# Social details for the jekyll-seo-tag gem
social:
  name: Kasper Birkelund
  links:

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Github
  - LinkedIn